name: build
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Test
        run: go test -v ./...

      - name: Go Coverage Badge  # Pass the `coverage.out` output to this action
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: coverage.out

